---
#
# Ansible managed
#
repository:
  description: Automated testing of look and feel for your responsive websites.
  homepage: https://buluma.github.io/
  topics: galen, python, sudo, ansible, molecule, playbook
